//
// TaskInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaskInput: Codable, JSONEncodable, Hashable {

    public enum Feedback: String, Codable, CaseIterable {
        case onTime = "on_time"
        case earlier = "earlier"
        case later = "later"
    }
    /** Descrição da tarefa. */
    public var description: String
    /** Data em que a tarefa foi realizada. */
    public var date: Date
    /** Feedback sobre a realização da tarefa. */
    public var feedback: Feedback?

    public init(description: String, date: Date, feedback: Feedback? = nil) {
        self.description = description
        self.date = date
        self.feedback = feedback
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case date
        case feedback
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(description, forKey: .description)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(feedback, forKey: .feedback)
    }
}

